name: Deployment Workflow

on:
  push:
    branches: [develop]

env:
  PROJECT_ROOT: '/var/www/mental-wellness-backend'
  TEST_CONFIG: '/var/.deploy_configs/mental-wellness-backend/test'
  DEV_CONFIG: '/var/.deploy_configs/mental-wellness-backend/dev'
  PM2_PROCESS: 'mental-wellness-backend-dev'

jobs:
  test:
    name: test
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies and copy config files.
        run: cp -r $PROJECT_ROOT/node_modules ./ && npm install && cp -r $TEST_CONFIG/. ./
      - name: build
        run: npm run build
      - name: Run test build.
        run: npm run start:test && echo "Basic setup tested successfully" && sleep 2
  deploy:
    name: deploy
    needs: test
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Change Directory to project root
        run: cd $PROJECT_ROOT && pwd
      - name: Pull code from git
        run: git fetch && git pull
      - name: Install Dependencies and copy config files.
        run: npm install && cp -r $DEV_CONFIG/. ./
      - name: Make dev build.
        run: npm run build
      - name: restart pm2 process.
        run: pm2 restart $PM2_PROCESS && pm2 log $PM2_PROCESS & sleep 30; kill -INT %+ && echo "Deployment completed successfully" && sleep 2
